package com.lonewolf.memeStream.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiModelProperty.AccessMode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * <p>
 * This class encapsulates model for determining Review about X-Meme
 * </p>
 * 
 * @author Subham
 * @version 2.0
 * @since 1.0
 * @see {@link com.lonewolf.memeStream.controller.MemeController}
 * @see {@link com.lonewolf.memeStream.repository.ReviewRepository}
 */
@ApiModel
@ToString
@NoArgsConstructor
@Entity
@Table(name = "reviews")
public class Review {
	@ApiModelProperty(accessMode = AccessMode.READ_ONLY, example = "1", notes = "Unique autogenerated ID of each review")
	@Getter
	@Id
	@Column(name = "review_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;

	@ApiModelProperty(accessMode = AccessMode.READ_WRITE, example = "John Doe", notes = "Name of Person who posted review")
	@Column(name = "reviewer_name")
	@Getter
	@Setter
	private String reviewer;

	@ApiModelProperty(accessMode = AccessMode.READ_WRITE, example = "X-Meme is best", notes = "Review posted by a user")
	@Column(name = "review_content", nullable = false)
	@Getter
	@Setter
	private String comment;

	@ApiModelProperty(accessMode = AccessMode.READ_WRITE, example = "3", notes = "Stars given by user, mininmum 1, maximum 5")
	@Column(name = "stars", nullable = false)
	@Getter
	@Setter
	private int stars;
}
